### ISSUE TITLE
Properties not set in the seafileAPI constructor

### ISSUE THREAD

**Issue by bastiencyr** [haiwen/seafile-js#345]
Hey, 
I use webpack but it may be unrelated. 
When I try this code:
```javascript
const { SeafileAPI } = require('seafile-js')
const seafileAPI = new SeafileAPI(server, username, password)
seafileAPI.login().then((response) => {
})
```
It doesn't work. The code run in a Thunderbird extension.
 But if I add this line:
```javascript
seafileAPI.init({ server: server.value, username: username.value, password: password.value });
```
It works like a charm ! It's just like the server, username and password properties are not set.
I didn't try without webpack.

**Comment by bastiencyr** [comment]
OK it is probably a duplicate of #273, the readme.md should be updated to match the new interface.

**Comment by Michael18811380328** [comment]
Thank you for your feedback. This issue has been fixed in https://github.com/haiwen/seafile-js/pull/389.
